# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_icon_menu = QtWidgets.QWidget(self.centralwidget)
        self.widget_icon_menu.setStyleSheet("QWidget{\n"
"    background-color:rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border:none;\n"
"    height:30px;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(218,218,218);\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.widget_icon_menu.setObjectName("widget_icon_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_icon_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_icon_menu)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icons/todolist.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_home = QtWidgets.QPushButton(self.widget_icon_menu)
        self.pushButton_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/homepage_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/homepage_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_home.setIcon(icon)
        self.pushButton_home.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_home.setCheckable(True)
        self.pushButton_home.setAutoExclusive(True)
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout.addWidget(self.pushButton_home)
        self.pushButton_dashboard = QtWidgets.QPushButton(self.widget_icon_menu)
        self.pushButton_dashboard.setAutoFillBackground(False)
        self.pushButton_dashboard.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/dashboard_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/dashboard_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_dashboard.setIcon(icon1)
        self.pushButton_dashboard.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_dashboard.setCheckable(True)
        self.pushButton_dashboard.setAutoExclusive(True)
        self.pushButton_dashboard.setObjectName("pushButton_dashboard")
        self.verticalLayout.addWidget(self.pushButton_dashboard)
        self.pushButton_users = QtWidgets.QPushButton(self.widget_icon_menu)
        self.pushButton_users.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/users_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/users_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_users.setIcon(icon2)
        self.pushButton_users.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_users.setCheckable(True)
        self.pushButton_users.setAutoExclusive(True)
        self.pushButton_users.setObjectName("pushButton_users")
        self.verticalLayout.addWidget(self.pushButton_users)
        self.pushButton_settings = QtWidgets.QPushButton(self.widget_icon_menu)
        self.pushButton_settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/settings_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/settings_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_settings.setIcon(icon3)
        self.pushButton_settings.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_settings.setCheckable(True)
        self.pushButton_settings.setAutoExclusive(True)
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.verticalLayout.addWidget(self.pushButton_settings)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 336, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_exit = QtWidgets.QPushButton(self.widget_icon_menu)
        self.pushButton_exit.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/close_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/close_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_exit.setIcon(icon4)
        self.pushButton_exit.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_exit.setCheckable(True)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout_3.addWidget(self.pushButton_exit)
        self.gridLayout.addWidget(self.widget_icon_menu, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_change = QtWidgets.QPushButton(self.widget)
        self.pushButton_change.setStyleSheet("border:none;")
        self.pushButton_change.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/menu_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_change.setIcon(icon5)
        self.pushButton_change.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_change.setCheckable(True)
        self.pushButton_change.setAutoExclusive(False)
        self.pushButton_change.setObjectName("pushButton_change")
        self.horizontalLayout_3.addWidget(self.pushButton_change)
        spacerItem1 = QtWidgets.QSpacerItem(224, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.pushButton_search = QtWidgets.QPushButton(self.widget)
        self.pushButton_search.setStyleSheet("border:none;")
        self.pushButton_search.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_search.setIcon(icon6)
        self.pushButton_search.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(224, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_user = QtWidgets.QPushButton(self.widget)
        self.pushButton_user.setStyleSheet("border:none;")
        self.pushButton_user.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/profile_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/profile_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_user.setIcon(icon7)
        self.pushButton_user.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_user.setObjectName("pushButton_user")
        self.horizontalLayout_3.addWidget(self.pushButton_user)
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label_4 = QtWidgets.QLabel(self.page_home)
        self.label_4.setGeometry(QtCore.QRect(460, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page_home)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 60, 331, 251))
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
"    border: 2px solid #ccc; /* Takvim çerçevesi rengi */\n"
"    border-radius: 5px; /* Köşeleri yuvarlat */\n"
"    background-color: #B8E2FF; /* Arka plan rengi */\n"
"    font: 12pt;\n"
"}\n"
"/*\n"
"QCalendarWidget QcalenderWidget{\n"
"        alternate-background-color: B8E2FF;\n"
"}?*/\n"
"\n"
"/* Takvim başlığı */\n"
"QCalendarWidget QAbstractItemView {\n"
"    background-color: #e0e0e0; /* Başlık arka plan rengi */\n"
"    color: #333; /* Başlık metin rengi */\n"
"    selection-color: white; /* Seçili tarih metin rengi */\n"
"    selection-background-color: #0078d7; /* Seçili tarih arka plan rengi */\n"
"}\n"
"\n"
"/* Takvim içeriği */\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #fff; /* İçerik arka plan rengi */\n"
"    border: 2px solid #B8E2FF;\n"
"    border-bottom: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* Takvim navigasyon butonları */\n"
"QCalendarWidget QToolButton {\n"
"    background-color: #ffffff; /* Navigasyon butonları arka plan rengi */\n"
"    color: black; /* Navigasyon butonları metin rengi */\n"
"    border: none; /* Kenarlık yok */\n"
"    padding: 5px; /* Buton içeriği boşluğu */\n"
"    width: 35px; /* Buton genişliği */\n"
"    height: 20px; /* Buton yüksekliği */\n"
"}\n"
"\n"
"/* Hover etkisi */\n"
"QCalendarWidget QToolButton:hover {\n"
"    background-color: #005ea2; /* Hover rengi */\n"
"}\n"
"\n"
"/* Seçili tarih */\n"
"QCalendarWidget QToolButton:selected {\n"
"    background-color: #003f76; /* Seçili buton rengi */\n"
"}\n"
"/* Önceki ay ve sonraki ay butonları */\n"
"QCalendarWidget QToolButton#qt_calendar_prevmonth {\n"
"    background-color: transparent; /* Önceki ay butonu arka plan rengi */\n"
"    color: white; /* Önceki ay butonu metin rengi */\n"
"    border: none; /* Kenarlık yok */\n"
"    padding: 5px; /* Buton içeriği boşluğu */\n"
"    min-width: 13px; /* Buton genişliği */\n"
"    max-width: 13px;\n"
"    min-height: 13px;/* Buton yüksekliği */\n"
"    max-height: 13px; \n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton#qt_calendar_nextmonth {\n"
"    background-color: transparent; /* Sonraki ay butonu arka plan rengi */\n"
"    color: white; /* Sonraki ay butonu metin rengi */\n"
"    border: none; /* Kenarlık yok */\n"
"    padding: 5px; /* Buton içeriği boşluğu */\n"
"    min-width: 13px; /* Buton genişliği */\n"
"    max-width: 13px;\n"
"    min-height: 13px;/* Buton yüksekliği */\n"
"    max-height: 13px; \n"
"    margin-right: 5px;\n"
"}\n"
"/* Ay ve yıl bilgisi */\n"
"QCalendarWidget QComboBox {\n"
"    min-width: 100px; /* Minimum genişlik */\n"
"    min-height: 30px; /* Minimum yükseklik */\n"
"    padding: 5px; /* Buton içeriği boşluğu */\n"
"    font-size: 13px; /* Yazı tipi boyutu */\n"
"}\n"
"")
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton = QtWidgets.QPushButton(self.page_home)
        self.pushButton.setGeometry(QtCore.QRect(320, 320, 101, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #333; \n"
"    background-color: #f0f0f0; \n"
"    border: 2px solid #fff6f4; \n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0; \n"
"    border-color: #e0e0e0; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0; \n"
"    border-color: #d0d0d0; \n"
"    border-style: inset;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_home)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 500, 261, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #333; \n"
"    background-color: #f0f0f0; \n"
"    border: 2px solid #fff6f4; \n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0; \n"
"    border-color: #e0e0e0; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0; \n"
"    border-color: #d0d0d0; \n"
"    border-style: inset;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.page_home)
        self.listWidget.setGeometry(QtCore.QRect(40, 320, 261, 171))
        self.listWidget.setObjectName("listWidget")
        self.label_8 = QtWidgets.QLabel(self.page_home)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 351, 41))
        self.label_8.setStyleSheet("border-radius: 10px;\n"
"font-size: 24px;\n"
"background: #01BFFF;\n"
"Color: white;\n"
"font: 11pt;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_home)
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.label_5 = QtWidgets.QLabel(self.page_dashboard)
        self.label_5.setGeometry(QtCore.QRect(240, 210, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.page_dashboard)
        self.label_9.setGeometry(QtCore.QRect(50, 30, 611, 71))
        self.label_9.setStyleSheet("QLabel {\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"    background-color: #f0f0f0;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background-color: #e0e0e0;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_dashboard)
        self.page_users = QtWidgets.QWidget()
        self.page_users.setObjectName("page_users")
        self.label_6 = QtWidgets.QLabel(self.page_users)
        self.label_6.setGeometry(QtCore.QRect(260, 240, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_users)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.label_7 = QtWidgets.QLabel(self.page_settings)
        self.label_7.setGeometry(QtCore.QRect(270, 290, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_settings)
        self.page_search = QtWidgets.QWidget()
        self.page_search.setObjectName("page_search")
        self.label_10 = QtWidgets.QLabel(self.page_search)
        self.label_10.setGeometry(QtCore.QRect(310, 230, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_search)
        self.page_profile = QtWidgets.QWidget()
        self.page_profile.setObjectName("page_profile")
        self.label_11 = QtWidgets.QLabel(self.page_profile)
        self.label_11.setGeometry(QtCore.QRect(240, 210, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page_profile)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_full_menu = QtWidgets.QWidget(self.centralwidget)
        self.widget_full_menu.setStyleSheet("QWidget{\n"
"    background-color:rgb(255,255,255);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color:black;\n"
"    text-align:left;\n"
"    border:none;\n"
"    height:30px;\n"
"    padding-left:10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: rgb(218,218,218);\n"
"    color: black;\n"
"    font-weight:bold;\n"
"}")
        self.widget_full_menu.setObjectName("widget_full_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_full_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_full_menu)
        self.label_2.setMinimumSize(QtCore.QSize(50, 50))
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/icons/todolist.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_full_menu)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 9, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_home2 = QtWidgets.QPushButton(self.widget_full_menu)
        self.pushButton_home2.setIcon(icon)
        self.pushButton_home2.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_home2.setCheckable(True)
        self.pushButton_home2.setAutoExclusive(True)
        self.pushButton_home2.setObjectName("pushButton_home2")
        self.verticalLayout_2.addWidget(self.pushButton_home2)
        self.pushButton_dashboard2 = QtWidgets.QPushButton(self.widget_full_menu)
        self.pushButton_dashboard2.setIcon(icon1)
        self.pushButton_dashboard2.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_dashboard2.setCheckable(True)
        self.pushButton_dashboard2.setAutoExclusive(True)
        self.pushButton_dashboard2.setObjectName("pushButton_dashboard2")
        self.verticalLayout_2.addWidget(self.pushButton_dashboard2)
        self.pushButton_users2 = QtWidgets.QPushButton(self.widget_full_menu)
        self.pushButton_users2.setIcon(icon2)
        self.pushButton_users2.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_users2.setCheckable(True)
        self.pushButton_users2.setAutoExclusive(True)
        self.pushButton_users2.setObjectName("pushButton_users2")
        self.verticalLayout_2.addWidget(self.pushButton_users2)
        self.pushButton_settings2 = QtWidgets.QPushButton(self.widget_full_menu)
        self.pushButton_settings2.setIcon(icon3)
        self.pushButton_settings2.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_settings2.setCheckable(True)
        self.pushButton_settings2.setAutoExclusive(True)
        self.pushButton_settings2.setObjectName("pushButton_settings2")
        self.verticalLayout_2.addWidget(self.pushButton_settings2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 295, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.pushButton_exit2 = QtWidgets.QPushButton(self.widget_full_menu)
        self.pushButton_exit2.setIcon(icon4)
        self.pushButton_exit2.setIconSize(QtCore.QSize(14, 14))
        self.pushButton_exit2.setObjectName("pushButton_exit2")
        self.verticalLayout_4.addWidget(self.pushButton_exit2)
        self.gridLayout.addWidget(self.widget_full_menu, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.pushButton_change.toggled['bool'].connect(self.widget_icon_menu.setVisible) # type: ignore
        self.pushButton_change.toggled['bool'].connect(self.widget_full_menu.setHidden) # type: ignore
        self.pushButton_home.toggled['bool'].connect(self.pushButton_home2.setChecked) # type: ignore
        self.pushButton_dashboard.toggled['bool'].connect(self.pushButton_dashboard2.setChecked) # type: ignore
        self.pushButton_users.toggled['bool'].connect(self.pushButton_users2.setChecked) # type: ignore
        self.pushButton_settings.toggled['bool'].connect(self.pushButton_settings2.setChecked) # type: ignore
        self.pushButton_home2.toggled['bool'].connect(self.pushButton_home.setChecked) # type: ignore
        self.pushButton_dashboard2.toggled['bool'].connect(self.pushButton_dashboard.setChecked) # type: ignore
        self.pushButton_users2.toggled['bool'].connect(self.pushButton_users.setChecked) # type: ignore
        self.pushButton_settings2.toggled['bool'].connect(self.pushButton_settings.setChecked) # type: ignore
        self.pushButton_exit.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton_exit2.toggled['bool'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_search.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.label_4.setText(_translate("MainWindow", "Home Page"))
        self.pushButton.setText(_translate("MainWindow", "Add New"))
        self.pushButton_2.setText(_translate("MainWindow", "Save Changes"))
        self.label_8.setText(_translate("MainWindow", "Daily Task Planner"))
        self.label_5.setText(_translate("MainWindow", "Dashboard Page"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Users Page"))
        self.label_7.setText(_translate("MainWindow", "Settings Page"))
        self.label_10.setText(_translate("MainWindow", "Search Page"))
        self.label_11.setText(_translate("MainWindow", "Profile Page"))
        self.label_3.setText(_translate("MainWindow", "SideBar"))
        self.pushButton_home2.setText(_translate("MainWindow", "Home"))
        self.pushButton_dashboard2.setText(_translate("MainWindow", "Dashboard"))
        self.pushButton_users2.setText(_translate("MainWindow", "Users"))
        self.pushButton_settings2.setText(_translate("MainWindow", "Settings"))
        self.pushButton_exit2.setText(_translate("MainWindow", "Exit"))
import resource_rc
