"""Description of the migration

Revision ID: e4f99ac11216
Revises: 
Create Date: 2024-04-17 10:59:48.285268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4f99ac11216'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tasks', 'due_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'categories',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.LargeBinary(length=60),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(length=60),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tasks', 'categories',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
