"""Description of the migration

Revision ID: ef9fdf5726d3
Revises: e4f99ac11216
Create Date: 2024-04-17 11:53:18.102843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef9fdf5726d3'
down_revision: Union[str, None] = 'e4f99ac11216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
